### ISSUE TITLE
How to generate the synthetic data

### ISSUE THREAD

**Issue by tranxuantuyen** [bpiyush/TestOfTime#4]
Hi, thanks you for releasing the code

Could you please share source code / the way that you use to generate the synthetic data. Many thanks

**Comment by bpiyush** [comment]
Hi! Apologies for the late reply. The notification email went into spam.

I have created a simple notebook [here](https://github.com/bpiyush/TestOfTime/blob/main/notebooks/generate_synthetic_data_example.ipynb) to generate a single example synthetic video. It can be extended to generate lots of examples with randomized parameters. Hope this helps.

**Comment by tranxuantuyen** [comment]
That's great, thank you a lot
